frontend:
  replicaCount: 2
  image:
    repository: muhammadsaadkhan5/google-web
    tag: frontend

checkout:
  replicaCount: 1
  image:
    repository: muhammadsaadkhan5/google-web
    tag: checkout

shoppingassistant:
  replicaCount: 1
  image:
    repository: muhammadsaadkhan5/google-web
    tag: shoppingassistant

adservice:
  replicaCount: 1
  image:
    repository: muhammadsaadkhan5/google-web
    tag: add

email:
  replicaCount: 1
  image:
    repository: muhammadsaadkhan5/google-web
    tag: email

payment:
  replicaCount: 1
  image:
    repository: muhammadsaadkhan5/google-web
    tag: payment

shipping:
  replicaCount: 1
  image:
    repository: muhammadsaadkhan5/google-web
    tag: shipping

recommendation:
  replicaCount: 1
  image:
    repository: muhammadsaadkhan5/google-web
    tag: recommendation

cart:
  replicaCount: 2
  image:
    repository: muhammadsaadkhan5/google-web
    tag: cart

product:
  replicaCount: 2
  image:
    repository: muhammadsaadkhan5/google-web
    tag: prod
