AWSTemplateFormatVersion: '2010-09-09'
Description: Phase 4 - EC2 Launch Template

Parameters:
  LaunchTemplateName:
    Type: String
    Default: MyLaunchTemplate
    Description: Name of the Launch Template

  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small
      - t3.medium

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Existing EC2 Key Pair

  SecurityStackName:
    Type: String
    Description: Name of the Security Stack

Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Ref LaunchTemplateName
      LaunchTemplateData:
        ImageId: !Ref LatestAmiId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyPairName

        IamInstanceProfile:
          Name:
            Fn::ImportValue:
              Fn::Sub: "${SecurityStackName}-InstanceProfileName"
              
        SecurityGroupIds:
          - Fn::ImportValue:
              Fn::Sub: "${SecurityStackName}-EC2SecurityGroupId"
        UserData:
          Fn::Base64: |
            #!/bin/bash
            dnf update -y
            dnf install -y docker
            systemctl enable docker
            systemctl start docker
            usermod -aG docker ec2-user

Outputs:
  LaunchTemplateId:
    Description: Launch Template ID
    Value: !Ref LaunchTemplate
    Export:
      Name: !Sub "${AWS::StackName}-LaunchTemplateId"

  LaunchTemplateLatestVersion:
    Description: Latest Launch Template Version
    Value: !GetAtt LaunchTemplate.LatestVersionNumber
    Export:
      Name: !Sub "${AWS::StackName}-LaunchTemplateLatestVersion"